"
" $Id: .vimrc,v 1.1 2003/02/01 23:49:04 huntert Exp huntert $
"
"set compatible
set nocompatible
let cpo_save=&cpo
set cpo=B
map! <xHome> <Home>
map! <xEnd> <End>
map! <S-xF4> <S-F4>
map! <S-xF3> <S-F3>
map! <S-xF2> <S-F2>
map! <S-xF1> <S-F1>
map! <xF4> <F4>
map! <xF3> <F3>
map! <xF2> <F2>
map! <xF1> <F1>
map <xHome> <Home>
map <xEnd> <End>
map <S-xF4> <S-F4>
map <S-xF3> <S-F3>
map <S-xF2> <S-F2>
map <S-xF1> <S-F1>
map <xF4> <F4>
map <xF3> <F3>
map <xF2> <F2>
map <xF1> <F1>
"
" terminal munging
"
if &term == "xterm"
    set t_kb=
endif
if &term == "xterm-color"
    set t_kb=
endif
"
" color terminal setup
"
"if &term =~ "xterm"
if has("terminfo")
  set t_Co=8
  set t_Sf=[3%p1%dm
  set t_Sb=[4%p1%dm
"  vt220-color|xterm-co|xterm with ANSI colors:\
"          :pa#64:Co#8:AF=\E[3%dm:AB=\E[4%dm:op=\E[39;49m:tc=vt220:
else
  set t_Co=8
  set t_Sf=[3%dm
  set t_Sb=[4%dm
endif
"endif
let &cpo=cpo_save
unlet cpo_save
set autoindent
set backspace=indent,eol,start
set shiftwidth=4
set smarttab
set wrapmargin=5
set textwidth=78
set formatoptions=vtqc
set showmatch
set comments=:\ \ #,s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-
set title
syntax on
highlight Normal guifg=yellow guibg=black
highlight Search gui=reverse guifg=white guibg=blue
"highlight Comment    ctermfg=white ctermbg=black
highlight Comment    ctermfg=7 ctermbg=black
highlight Statement  ctermfg=green 			" keywords
highlight Constant   ctermfg=cyan
highlight Identifier ctermfg=yellow			" variable
highlight Type       ctermfg=red			" package name
highlight Special    ctermfg=magenta			" regex escape?
"
" 0 - black	1 - dk red	2 - dk green	3 - dk brown/yellow
" 4 - dk blue	5 - dk purple	6 - dk cyan	7 - grey
" also bright:
" red green yellow blue magenta cyan darkgrey
"
"
highlight PreProc        term=underline  ctermfg=5  guifg=Purple
" Ignore         cterm=bold  ctermfg=7  guifg=bg
" Error          term=reverse  cterm=bold  ctermfg=7  ctermbg=1  guifg=White guibg=Red
" Todo           term=standout  ctermfg=0  ctermbg=3 guifg=Blue  guibg=Yellow
"
" Vim color file - breeze
" Generated by http://bytefluent.com/vivify 2017-07-13
"set background=dark
"if version > 580
"	hi clear
"	if exists("syntax_on")
"		syntax reset
"	endif
"endif
"
""set t_Co=256
""let g:colors_name = "breeze"

"hi SignColumn -- no settings --
"hi TabLineSel -- no settings --
"hi CTagsMember -- no settings --
"hi CTagsGlobalConstant -- no settings --
"hi PMenuSbar -- no settings --
"hi Normal guifg=#ffffff guibg=#005c70 guisp=#005c70 gui=NONE ctermfg=15 ctermbg=6 cterm=NONE
"hi CTagsImport -- no settings --
"hi CTagsGlobalVariable -- no settings --
"hi SpellRare -- no settings --
"hi EnumerationValue -- no settings --
"hi Float -- no settings --
"hi CursorLine -- no settings --
"hi Union -- no settings --
"hi TabLineFill -- no settings --
"hi VisualNOS -- no settings --
"hi CursorColumn -- no settings --
"hi EnumerationName -- no settings --
"hi SpellCap -- no settings --
"hi SpellLocal -- no settings --
"hi DefinedName -- no settings --
"hi MatchParen -- no settings --
"hi LocalVariable -- no settings --
"hi SpellBad -- no settings --
"hi CTagsClass -- no settings --
"hi TabLine -- no settings --
"hi clear -- no settings --
"hi default -- no settings --
"hi IncSearch guifg=#60ffff guibg=#6060ff guisp=#6060ff gui=NONE ctermfg=87 ctermbg=63 cterm=NONE
""hi WildMenu guifg=#000000 guibg=#00c8f0 guisp=#00c8f0 gui=NONE ctermfg=NONE ctermbg=45 cterm=NONE
""hi SpecialComment guifg=#ffd074 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi Typedef guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi Title guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=15 ctermbg=NONE cterm=NONE
""hi Folded guifg=#ffffff guibg=#0088c0 guisp=#0088c0 gui=NONE ctermfg=15 ctermbg=4 cterm=NONE
""hi PreCondit guifg=#ffc0ff guibg=NONE guisp=NONE gui=NONE ctermfg=219 ctermbg=NONE cterm=NONE
""hi Include guifg=#ffc0ff guibg=NONE guisp=NONE gui=NONE ctermfg=219 ctermbg=NONE cterm=NONE
""hi StatusLineNC guifg=#606080 guibg=#d0d0e0 guisp=#d0d0e0 gui=NONE ctermfg=60 ctermbg=146 cterm=NONE
""hi NonText guifg=#00c0c0 guibg=#006276 guisp=#006276 gui=NONE ctermfg=4 ctermbg=6 cterm=NONE
""hi DiffText guifg=#ffff00 guibg=#000000 guisp=#000000 gui=NONE ctermfg=11 ctermbg=NONE cterm=NONE
""hi ErrorMsg guifg=#ffffff guibg=#ff40a0 guisp=#ff40a0 gui=NONE ctermfg=15 ctermbg=13 cterm=NONE
""hi Ignore guifg=#006074 guibg=NONE guisp=NONE gui=NONE ctermfg=6 ctermbg=NONE cterm=NONE
""hi Debug guifg=#ffd074 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
"hi Identifier guifg=#cacaff guibg=NONE guisp=NONE gui=NONE ctermfg=189 ctermbg=NONE cterm=NONE
""hi SpecialChar guifg=#ffd074 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi Conditional guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi StorageClass guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi Todo guifg=#ffb0b0 guibg=NONE guisp=NONE gui=NONE ctermfg=217 ctermbg=NONE cterm=NONE
""hi Special guifg=#ffd074 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi LineNr guifg=#60a8bc guibg=NONE guisp=NONE gui=NONE ctermfg=73 ctermbg=NONE cterm=NONE
""hi StatusLine guifg=#000000 guibg=#d0d0e0 guisp=#d0d0e0 gui=NONE ctermfg=NONE ctermbg=146 cterm=NONE
""hi Label guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi PMenuSel guifg=#000000 guibg=#d0d0e0 guisp=#d0d0e0 gui=NONE ctermfg=NONE ctermbg=146 cterm=NONE
"hi Search guifg=#ffffff guibg=#6060ff guisp=#6060ff gui=NONE ctermfg=15 ctermbg=63 cterm=NONE
""hi Delimiter guifg=#ffd074 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
"hi Statement guifg=#ffff80 guibg=NONE guisp=NONE gui=NONE ctermfg=228 ctermbg=NONE cterm=NONE
"hi Comment guifg=#c8d0d0 guibg=NONE guisp=NONE gui=NONE ctermfg=152 ctermbg=NONE cterm=NONE
hi Character guifg=#60ffff guibg=NONE guisp=NONE gui=NONE ctermfg=87 ctermbg=NONE cterm=NONE
""hi Number guifg=#60ffff guibg=NONE guisp=NONE gui=NONE ctermfg=87 ctermbg=NONE cterm=NONE
""hi Boolean guifg=#ffff80 guibg=NONE guisp=NONE gui=NONE ctermfg=228 ctermbg=NONE cterm=NONE
""hi Operator guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi Question guifg=#ffff60 guibg=NONE guisp=NONE gui=NONE ctermfg=227 ctermbg=NONE cterm=NONE
""hi WarningMsg guifg=#ffffff guibg=#ff40a0 guisp=#ff40a0 gui=NONE ctermfg=15 ctermbg=13 cterm=NONE
""hi DiffDelete guifg=#60ff60 guibg=#000000 guisp=#000000 gui=NONE ctermfg=83 ctermbg=NONE cterm=NONE
""hi ModeMsg guifg=#60ffff guibg=NONE guisp=NONE gui=NONE ctermfg=87 ctermbg=NONE cterm=NONE
""hi Define guifg=#ffc0ff guibg=NONE guisp=NONE gui=NONE ctermfg=219 ctermbg=NONE cterm=NONE
""hi Function guifg=#cacaff guibg=NONE guisp=NONE gui=NONE ctermfg=189 ctermbg=NONE cterm=NONE
""hi FoldColumn guifg=#60e0e0 guibg=#006c7f guisp=#006c7f gui=NONE ctermfg=80 ctermbg=6 cterm=NONE
""hi PreProc guifg=#ffc0ff guibg=NONE guisp=NONE gui=NONE ctermfg=219 ctermbg=NONE cterm=NONE
""hi Visual guifg=#ffffff guibg=#6060d0 guisp=#6060d0 gui=NONE ctermfg=15 ctermbg=62 cterm=NONE
""hi MoreMsg guifg=#ffc0ff guibg=NONE guisp=NONE gui=NONE ctermfg=219 ctermbg=NONE cterm=NONE
""hi VertSplit guifg=#606080 guibg=#d0d0e0 guisp=#d0d0e0 gui=NONE ctermfg=60 ctermbg=146 cterm=NONE
""hi Exception guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi Keyword guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
"hi Type guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi DiffChange guifg=#ffffff guibg=#000000 guisp=#000000 gui=NONE ctermfg=15 ctermbg=NONE cterm=NONE
""hi Cursor guifg=#ffffff guibg=#d86020 guisp=#d86020 gui=NONE ctermfg=15 ctermbg=166 cterm=NONE
""hi Error guifg=#ffffff guibg=#ff40a0 guisp=#ff40a0 gui=NONE ctermfg=15 ctermbg=13 cterm=NONE
""hi PMenu guifg=#606080 guibg=#d0d0e0 guisp=#d0d0e0 gui=NONE ctermfg=60 ctermbg=146 cterm=NONE
""hi SpecialKey guifg=#e0a0ff guibg=NONE guisp=NONE gui=NONE ctermfg=183 ctermbg=NONE cterm=NONE
"hi Constant guifg=#60ffff guibg=NONE guisp=NONE gui=NONE ctermfg=87 ctermbg=NONE cterm=NONE
""hi Tag guifg=#ffd074 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi String guifg=#60ffff guibg=NONE guisp=NONE gui=NONE ctermfg=87 ctermbg=NONE cterm=NONE
""hi PMenuThumb guifg=NONE guibg=#60a8bc guisp=#60a8bc gui=NONE ctermfg=NONE ctermbg=73 cterm=NONE
""hi Repeat guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi Directory guifg=#00e0ff guibg=NONE guisp=NONE gui=NONE ctermfg=45 ctermbg=NONE cterm=NONE
""hi Structure guifg=#80ffa0 guibg=NONE guisp=NONE gui=NONE ctermfg=121 ctermbg=NONE cterm=NONE
""hi Macro guifg=#ffc0ff guibg=NONE guisp=NONE gui=NONE ctermfg=219 ctermbg=NONE cterm=NONE
""hi Underlined guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=15 ctermbg=NONE cterm=NONE
""hi DiffAdd guifg=#60ff60 guibg=#000000 guisp=#000000 gui=NONE ctermfg=83 ctermbg=NONE cterm=NONE
""hi cursorim guifg=#ffffff guibg=#e000b0 guisp=#e000b0 gui=NONE ctermfg=15 ctermbg=163 cterm=NONE
""hi mbenormal guifg=#cfbfad guibg=#2e2e3f guisp=#2e2e3f gui=NONE ctermfg=187 ctermbg=237 cterm=NONE
""hi perlspecialstring guifg=#c080d0 guibg=#404040 guisp=#404040 gui=NONE ctermfg=176 ctermbg=238 cterm=NONE
""hi doxygenspecial guifg=#fdd090 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi mbechanged guifg=#eeeeee guibg=#2e2e3f guisp=#2e2e3f gui=NONE ctermfg=255 ctermbg=237 cterm=NONE
""hi mbevisiblechanged guifg=#eeeeee guibg=#4e4e8f guisp=#4e4e8f gui=NONE ctermfg=255 ctermbg=60 cterm=NONE
""hi doxygenparam guifg=#fdd090 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi doxygensmallspecial guifg=#fdd090 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi doxygenprev guifg=#fdd090 guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi perlspecialmatch guifg=#c080d0 guibg=#404040 guisp=#404040 gui=NONE ctermfg=176 ctermbg=238 cterm=NONE
""hi cformat guifg=#c080d0 guibg=#404040 guisp=#404040 gui=NONE ctermfg=176 ctermbg=238 cterm=NONE
""hi lcursor guifg=#ffffff guibg=#e000b0 guisp=#e000b0 gui=NONE ctermfg=15 ctermbg=163 cterm=NONE
""hi doxygenspecialmultilinedesc guifg=#ad600b guibg=NONE guisp=NONE gui=NONE ctermfg=130 ctermbg=NONE cterm=NONE
""hi taglisttagname guifg=#808bed guibg=NONE guisp=NONE gui=NONE ctermfg=105 ctermbg=NONE cterm=NONE
""hi doxygenbrief guifg=#fdab60 guibg=NONE guisp=NONE gui=NONE ctermfg=215 ctermbg=NONE cterm=NONE
""hi mbevisiblenormal guifg=#cfcfcd guibg=#4e4e8f guisp=#4e4e8f gui=NONE ctermfg=252 ctermbg=60 cterm=NONE
""hi user2 guifg=#7070a0 guibg=#3e3e5e guisp=#3e3e5e gui=NONE ctermfg=103 ctermbg=60 cterm=NONE
""hi user1 guifg=#00ff8b guibg=#3e3e5e guisp=#3e3e5e gui=NONE ctermfg=48 ctermbg=60 cterm=NONE
""hi doxygenspecialonelinedesc guifg=#ad600b guibg=NONE guisp=NONE gui=NONE ctermfg=130 ctermbg=NONE cterm=NONE
""hi doxygencomment guifg=#ad7b20 guibg=NONE guisp=NONE gui=NONE ctermfg=130 ctermbg=NONE cterm=NONE
""hi cspecialcharacter guifg=#c080d0 guibg=#404040 guisp=#404040 gui=NONE ctermfg=176 ctermbg=238 cterm=NONE
""hi pythonimport guifg=#009000 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE cterm=NONE
""hi pythonexception guifg=#f00000 guibg=NONE guisp=NONE gui=NONE ctermfg=196 ctermbg=NONE cterm=NONE
""hi pythonbuiltinfunction guifg=#009000 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE cterm=NONE
""hi pythonoperator guifg=#7e8aa2 guibg=NONE guisp=NONE gui=NONE ctermfg=103 ctermbg=NONE cterm=NONE
""hi pythonexclass guifg=#009000 guibg=NONE guisp=NONE gui=NONE ctermfg=28 ctermbg=NONE cterm=NONE
""hi pythonbuiltin guifg=#839496 guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE
""hi phpstringdouble guifg=#e2e4e5 guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
""hi htmltagname guifg=#e2e4e5 guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
""hi javascriptstrings guifg=#e2e4e5 guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
""hi htmlstring guifg=#e2e4e5 guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
""hi phpstringsingle guifg=#e2e4e5 guibg=NONE guisp=NONE gui=NONE ctermfg=254 ctermbg=NONE cterm=NONE
""hi stringdelimiter guifg=#556633 guibg=NONE guisp=NONE gui=NONE ctermfg=101 ctermbg=NONE cterm=NONE
""hi rubyregexp guifg=#dd0093 guibg=NONE guisp=NONE gui=NONE ctermfg=162 ctermbg=NONE cterm=NONE
""hi string guifg=#99ad6a guibg=NONE guisp=NONE gui=NONE ctermfg=107 ctermbg=NONE cterm=NONE
""hi constant guifg=#cf6a4c guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE
""hi normal guifg=#e8e8d3 guibg=#151515 guisp=#151515 gui=NONE ctermfg=187 ctermbg=233 cterm=NONE
""hi rubyinstancevariable guifg=#c6b6fe guibg=NONE guisp=NONE gui=NONE ctermfg=147 ctermbg=NONE cterm=NONE
""hi rubyclass guifg=#447799 guibg=NONE guisp=NONE gui=NONE ctermfg=67 ctermbg=NONE cterm=NONE
""hi identifier guifg=#c6b6ee guibg=NONE guisp=NONE gui=NONE ctermfg=183 ctermbg=NONE cterm=NONE
""hi comment guifg=#888888 guibg=NONE guisp=NONE gui=italic ctermfg=102 ctermbg=NONE cterm=NONE
""hi rubyregexpdelimiter guifg=#540063 guibg=NONE guisp=NONE gui=NONE ctermfg=53 ctermbg=NONE cterm=NONE
""hi rubyregexpspecial guifg=#a40073 guibg=NONE guisp=NONE gui=NONE ctermfg=126 ctermbg=NONE cterm=NONE
""hi rubypredefinedidentifier guifg=#de5577 guibg=NONE guisp=NONE gui=NONE ctermfg=168 ctermbg=NONE cterm=NONE
""hi function guifg=#fad07a guibg=NONE guisp=NONE gui=NONE ctermfg=222 ctermbg=NONE cterm=NONE
""hi directory guifg=#dad085 guibg=NONE guisp=NONE gui=NONE ctermfg=186 ctermbg=NONE cterm=NONE
""hi rubysymbol guifg=#7697d6 guibg=NONE guisp=NONE gui=NONE ctermfg=110 ctermbg=NONE cterm=NONE
""hi rubycontrol guifg=#7597c6 guibg=NONE guisp=NONE gui=NONE ctermfg=110 ctermbg=NONE cterm=NONE
""hi rubyidentifier guifg=#c6b6fe guibg=NONE guisp=NONE gui=NONE ctermfg=147 ctermbg=NONE cterm=NONE
""hi condtional guifg=#8fffff guibg=NONE guisp=NONE gui=NONE ctermfg=123 ctermbg=NONE cterm=NONE
""hi htmlitalic guifg=#D0D0D0 guibg=#1F1F1F guisp=#1F1F1F gui=italic ctermfg=252 ctermbg=234 cterm=NONE
""hi htmlboldunderlineitalic guifg=#D0D0D0 guibg=#1F1F1F guisp=#1F1F1F gui=bold,italic,underline ctermfg=252 ctermbg=234 cterm=bold,underline
""hi htmlbolditalic guifg=#D0D0D0 guibg=#1F1F1F guisp=#1F1F1F gui=bold,italic ctermfg=252 ctermbg=234 cterm=bold
""hi htmlunderlineitalic guifg=#D0D0D0 guibg=#1F1F1F guisp=#1F1F1F gui=italic,underline ctermfg=252 ctermbg=234 cterm=underline
""hi htmlbold guifg=#D0D0D0 guibg=#1F1F1F guisp=#1F1F1F gui=bold ctermfg=252 ctermbg=234 cterm=bold
""hi htmlboldunderline guifg=#D0D0D0 guibg=#1F1F1F guisp=#1F1F1F gui=bold,underline ctermfg=252 ctermbg=234 cterm=bold,underline
""hi htmlunderline guifg=#D0D0D0 guibg=#1F1F1F guisp=#1F1F1F gui=underline ctermfg=252 ctermbg=234 cterm=underline
"
" use :Man command
"runtime ftplugin/man/default.vim
"runtime ftplugin/man/default.vim
"
" doesn't seem to work on rm2, other v5 systems
"
if version >= 600
    runtime ftplugin/man.vim
endif
